environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "11"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

# Post-install test scripts.
test_script:
  - node --version
  - yarn --version
  - yarn run check-ci

# Don't actually build.
build: off

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
